services:
  flask-app:
    build:
      context: ./flask-app
    ports:
      - "5000:5000"

  redis:
    image: redis:alpine
    volumes:
      - ./redis/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - "6379:6379"

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask-app
      - redis
