version: '3.8'

services:
  flask-app:
    build:
      context: ./flask-app
    networks:
      - app-network
    restart: always  

  redis:
    image: redis:alpine
    volumes:
      - ./redis/init.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - app-network
    restart: always

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80" 
    depends_on:
      - flask-app
      - redis
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
